# Generated by Django 3.2.16 on 2024-07-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240705_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeToTag',
        ),
    ]
