# Generated by Django 3.2.16 on 2024-07-05 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240705_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='amount',
        ),
        migrations.AddField(
            model_name='recipetoingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
