# Generated by Django 3.2.16 on 2024-07-07 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20240705_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetoingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientlist', to='api.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipetoingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientlist', to='api.recipe'),
        ),
    ]
