# Generated by Django 3.2.16 on 2024-07-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240707_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientAmount',
        ),
    ]
