# Generated by Django 3.2.16 on 2024-07-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foodgrammuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='foodgrammuser',
            name='avatar',
            field=models.ImageField(upload_to='users/avatar/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='foodgrammuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
