# Generated by Django 3.2.16 on 2024-07-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240703_1328'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foodgrammuser',
            managers=[
            ],
        ),
    ]
