# Generated by Django 3.2 on 2024-07-21 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgrammuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Выберите другой ник', regex='[\\w.@+-]+$')], verbose_name='Ник'),
        ),
    ]
