# Generated by Django 3.2 on 2024-07-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_foodgrammuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgrammuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ник'),
        ),
    ]
