# Generated by Django 3.2.15 on 2024-07-23 07:30

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_foodgrammuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foodgrammuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
